 import { Comment } from "../../../Types/Types"

export let Comments: Comment[] = [
    {
        userName: "ww",
        blogTitle: "BlogTitle: Second blog",
        blogIdNumber: 4,
        postTitle: "PostTitle: First Post in the second blog",
        postIdNumber: 6,
        fromUser: "jj",
        comment: "third comment to a post",
        commentIdNumber: 1,
        dateTimeStamp: "2/7/2024, 4:26:30 PM",
    },
    {
        userName: "ww",
        blogTitle: "BlogTitle: Second blog",
        blogIdNumber: 4,
        postTitle: "PostTitle: First Post in the second blog",
        postIdNumber: 6,
        fromUser: "ee",
        comment: "first comment to a post",
        commentIdNumber: 2,
        dateTimeStamp: "3/7/2024, 9:26:30 AM",
    },
    {
        userName: "ww",
        blogTitle: "BlogTitle: Second blog",
        blogIdNumber: 4,
        postTitle: "PostTitle: First Post in the second blog",
        postIdNumber: 6,
        fromUser: "ee",
        comment: "Second comment to a post",
        commentIdNumber: 3,
        dateTimeStamp: "3/7/2020, 3:26:30 PM",
    },
    {
        userName: "ee",
        blogTitle: "My computers",
        blogIdNumber: 2,
        postTitle: "First Post",
        postIdNumber: 2,
        fromUser: "ww",
        comment: "First comment to a post",
        commentIdNumber: 4,
        dateTimeStamp: "9/2/2014, 2:15:52 PM",
    },
    {
        userName: "ee",
        blogTitle: "My computers",
        blogIdNumber: 2,
        postTitle: "Second post",
        postIdNumber: 3,
        fromUser: "ww",
        comment: "bla bla, bla bla, bla bla, bla bla comment to Second post",
        commentIdNumber: 5,
        dateTimeStamp: "9/2/2016, 2:15:52 PM",
    },
    {
        userName: "jj", 
        blogTitle: "My cars",
        blogIdNumber: 1,
        postTitle: "First Post",
        postIdNumber: 1,
        fromUser: "ww",
        comment: "bla bla comment to First Post",
        commentIdNumber: 6,
        dateTimeStamp: "9/2/2015, 2:15:52 PM",
    },
]